// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/individual.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetQuery) Reset() {
	*x = GetQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_individual_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuery) ProtoMessage() {}

func (x *GetQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_individual_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuery.ProtoReflect.Descriptor instead.
func (*GetQuery) Descriptor() ([]byte, []int) {
	return file_proto_individual_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListQuery) Reset() {
	*x = ListQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_individual_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuery) ProtoMessage() {}

func (x *ListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_individual_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuery.ProtoReflect.Descriptor instead.
func (*ListQuery) Descriptor() ([]byte, []int) {
	return file_proto_individual_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Individual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth string `protobuf:"bytes,3,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Nationality string `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
}

func (x *Individual) Reset() {
	*x = Individual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_individual_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Individual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Individual) ProtoMessage() {}

func (x *Individual) ProtoReflect() protoreflect.Message {
	mi := &file_proto_individual_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Individual.ProtoReflect.Descriptor instead.
func (*Individual) Descriptor() ([]byte, []int) {
	return file_proto_individual_proto_rawDescGZIP(), []int{2}
}

func (x *Individual) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Individual) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Individual) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Individual) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

type Individuals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Individuals []*Individual `protobuf:"bytes,1,rep,name=individuals,proto3" json:"individuals,omitempty"`
}

func (x *Individuals) Reset() {
	*x = Individuals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_individual_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Individuals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Individuals) ProtoMessage() {}

func (x *Individuals) ProtoReflect() protoreflect.Message {
	mi := &file_proto_individual_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Individuals.ProtoReflect.Descriptor instead.
func (*Individuals) Descriptor() ([]byte, []int) {
	return file_proto_individual_proto_rawDescGZIP(), []int{3}
}

func (x *Individuals) GetIndividuals() []*Individual {
	if x != nil {
		return x.Individuals
	}
	return nil
}

var File_proto_individual_proto protoreflect.FileDescriptor

var file_proto_individual_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x74, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66,
	0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x0b, 0x49, 0x6e, 0x64, 0x69, 0x76,
	0x69, 0x64, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49, 0x6e,
	0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x73, 0x32, 0x9d, 0x01, 0x0a, 0x11, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x12, 0x09, 0x2e, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x0b, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x12, 0x0b, 0x2e, 0x49, 0x6e, 0x64,
	0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x1a, 0x0b, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69,
	0x64, 0x75, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x0a, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x0c, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75,
	0x61, 0x6c, 0x73, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d, 0x70, 0x65, 0x64, 0x72, 0x6f, 0x2e, 0x70,
	0x72, 0x61, 0x64, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x64, 0x69, 0x76, 0x69, 0x64, 0x75, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_individual_proto_rawDescOnce sync.Once
	file_proto_individual_proto_rawDescData = file_proto_individual_proto_rawDesc
)

func file_proto_individual_proto_rawDescGZIP() []byte {
	file_proto_individual_proto_rawDescOnce.Do(func() {
		file_proto_individual_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_individual_proto_rawDescData)
	})
	return file_proto_individual_proto_rawDescData
}

var file_proto_individual_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_individual_proto_goTypes = []interface{}{
	(*GetQuery)(nil),    // 0: GetQuery
	(*ListQuery)(nil),   // 1: ListQuery
	(*Individual)(nil),  // 2: Individual
	(*Individuals)(nil), // 3: Individuals
}
var file_proto_individual_proto_depIdxs = []int32{
	2, // 0: Individuals.individuals:type_name -> Individual
	0, // 1: IndividualService.GetIndividual:input_type -> GetQuery
	2, // 2: IndividualService.CreateIndividual:input_type -> Individual
	1, // 3: IndividualService.ListIndividuals:input_type -> ListQuery
	2, // 4: IndividualService.GetIndividual:output_type -> Individual
	2, // 5: IndividualService.CreateIndividual:output_type -> Individual
	3, // 6: IndividualService.ListIndividuals:output_type -> Individuals
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_individual_proto_init() }
func file_proto_individual_proto_init() {
	if File_proto_individual_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_individual_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_individual_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_individual_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Individual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_individual_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Individuals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_individual_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_individual_proto_goTypes,
		DependencyIndexes: file_proto_individual_proto_depIdxs,
		MessageInfos:      file_proto_individual_proto_msgTypes,
	}.Build()
	File_proto_individual_proto = out.File
	file_proto_individual_proto_rawDesc = nil
	file_proto_individual_proto_goTypes = nil
	file_proto_individual_proto_depIdxs = nil
}
